version: "2.4"
services:
  hermes:
    container_name: "hermes"
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=prod
